version: '3.8'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      - "3306:3306"
    container_name: CHAYAANI_DB
    volumes:
      - ./chayaani.sql:/docker-entrypoint-initdb.d/chayaani.sql
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    container_name: CHAYAANI_PIPELINE_JENKINS
    volumes:
      - ~/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker